version: '2'

volumes:
  db_data:
    driver: local
  grafana_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: ${IP_REDE}

services:
  zabbix-server:
    container_name: zabbix-server
    hostname: zabbix-server
    restart: unless-stopped
    image: zabbix/zabbix-server-pgsql:alpine-${ZABBIX_VERSION}-latest
    environment:
      - DB_SERVER_PORT=5433
      - DB_SERVER_HOST=postgresql
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
    ports:
      - ${PORT_ZBX_SERVER}:10051
    volumes:
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
    depends_on:
      - postgresql
    networks:
      app_net:
        ipv4_address: ${IP_ZBX_SERVER}

  zabbix-frontend:
    container_name: zabbix-frontend
    hostname: zabbix-frontend
    restart: unless-stopped
    image: zabbix/zabbix-web-apache-pgsql:alpine-${ZABBIX_VERSION}-latest
    environment:
      - DB_SERVER_PORT=5433
      - DB_SERVER_HOST=postgresql
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - PHP_TZ=America/Sao_Paulo
      - ZBX_SERVER_NAME=zabbix-server
    ports:
      - ${PORT_ZBX_FRONTEND}:80
      - ${PORT_ZBX_FRONTEND_SSL}:443
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/ssl/apache2:/etc/ssl/apache2:ro
    depends_on:
      - postgresql
      - zabbix-server
    networks:
      app_net:
        ipv4_address: ${IP_ZBX_FRONTEND}

  postgresql:
    container_name: postgresql
    hostname: postgresql
    restart: unless-stopped
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
    ports:
      - ${PORT_PGSQL}:5433
    volumes:
      - db_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_connections=1000"]
    networks:
      app_net:
        ipv4_address: ${IP_ZBX_PGSQL}
  
  zabbix-agent:
    container_name: zabbix-agent
    hostname: zabbix-agent
    restart: unless-stopped
    image: zabbix/zabbix-agent:alpine-${ZABBIX_VERSION}-latest
    environment:
      - ZBX_HOSTNAME=zabbix-agent
      - ZBX_DEBUGLEVEL=4
      - ZBX_ENABLEREMOTECOMMANDS=1
      - ZBX_SERVER_HOST=zabbix-server
    ports:
      - ${PORT_ZBX_AGENT}:10050
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
    depends_on:
      - zabbix-server
    networks:
      app_net:
        ipv4_address: ${IP_ZBX_AGENT}

  grafana:
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    image: monitoringartist/grafana-xxl:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - ${PORT_GRAFANA}:3000
    depends_on:
      - zabbix-frontend
    networks:
      app_net:
        ipv4_address: ${IP_GRAFANA}

  zapix:
    container_name: zapix
    hostname: zapix
    restart: unless-stopped
    build:
      context: ./zapix
    ports:
      - ${PORT_ZAPIX}:80
    depends_on:
      - zabbix-frontend
    networks:
      app_net:
        ipv4_address: ${IP_ZAPIX}

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    restart: unless-stopped
    image: thajeztah/pgadmin4
    ports:
      - ${PORT_PGADMIN}:5050
    volumes:
      - pgadmin_data:/pgadmin
    depends_on:
      - postgresql
    networks:
      app_net:
        ipv4_address: ${IP_PGADMIN}

  mailhog:
    container_name: mailhog
    hostname: mailhog
    restart: unless-stopped  
    image: mailhog/mailhog:v1.0.0
    environment:
      - MH_HOSTNAME=mailhog
    ports:
      - ${PORT_SMTP}:1025
      - ${PORT_WEBMAIL}:8025
    networks:
      app_net:
        ipv4_address: ${IP_MAIL}
